In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
a1 = np.arange(6)
print(a1)

[0 1 2 3 4 5]


In [ ]:
a2 = np.arange(1,10,2)
print(a2)

[1 3 5 7 9]


In [9]:
a3 = np.arange(10,60,10)
print(a3)

[10 20 30 40 50]
